### PR TITLE
Add foxglove bridge (internal PR for this fork)

### PR DESCRIPTION
**Pull request by achim-k**
PR for faster testing. Doesn't require approval to run CI

### CODE REVIEW

**Comment by achim-k** [comment]
@Tobias-Fischer I have created this PR for faster iteration (does not need approval to run CI)

- The `linux-aarch64` build still fails with the ROS_VERSION not set error (even though I manually set it in [3382ad1](https://github.com/defunctzombie/robostack-ros-noetic/pull/2/commits/3382ad1513e0602d57917800375a4ff3fec6d751))
- The other failing jobs fail on ros-babel-fish. It seems my patch is not applied? How can I interpret the following output?
```
Applying patch: /Users/runner/work/robostack-ros-noetic/robostack-ros-noetic/patch/ros-noetic-ros-babel-fish.patch
Applying patch: /Users/runner/work/robostack-ros-noetic/robostack-ros-noetic/patch/ros-noetic-ros-babel-fish.patch with args:
['-Np2', '-i', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmphk5iwzsk/ros-noetic-ros-babel-fish.patch.native', '--binary']
Patch analysis gives:
[[ RA-MD2LOVE ]] - [[                                   patch/ros-noetic-ros-babel-fish.patch ]]

Key:

R :: Reversible                       A :: Applicable
Y :: Build-prefix patch in use        M :: Minimal, non-amalgamated
D :: Dry-runnable                     N :: Patch level (1 is preferred)
L :: Patch level not-ambiguous        O :: Patch applies without offsets
V :: Patch applies without fuzz       E :: Patch applies without emitting to stderr
```

**Comment by Tobias-Fischer** [comment]
It seems there are a few different issues:
osx-64: 
```
$SRC_DIR/ros-noetic-ros-babel-fish/src/work/src/generation/providers/integrated_description_provider.cpp:8:10: fatal error: 'experimental/filesystem' file not found
[8036](https://github.com/defunctzombie/robostack-ros-noetic/actions/runs/4326392998/jobs/7553749419#step:16:8037)
#include <experimental/filesystem>
[8037](https://github.com/defunctzombie/robostack-ros-noetic/actions/runs/4326392998/jobs/7553749419#step:16:8038)
         ^~~~~~~~~~~~~~~~~~~~~~~~~
[8038](https://github.com/defunctzombie/robostack-ros-noetic/actions/runs/4326392998/jobs/7553749419#step:16:8039)
```
-> I think this is just <filesystem> in the newest clang

osx-arm64:
size_t and uint8_t are unknown types. Probably misses an include or the `std::`, see https://en.cppreference.com/w/cpp/types/size_t

win-64:
My best bet is that the line endings don't match. Windows is a pain in that regard .. do you have a Windows machine available to create a new patch? This might help.

**Comment by achim-k** [comment]
Got a step further. The remaining build failures are due to 
```
Make Error at CMakeLists.txt:152 (message):
  ROS_VERSION environment variable must be 1 or 2
```

@Tobias-Fischer do you have an idea what could be the problem here? Hardcoding the ROS_VERSION didn't work (https://github.com/defunctzombie/robostack-ros-noetic/pull/2/commits/3382ad1513e0602d57917800375a4ff3fec6d751)

**Comment by Tobias-Fischer** [comment]
Unfortunately I really don’t know and I won’t have time to properly look into it for quite some time. I think the easiest way forward is to patch it out, and I can take a look at fixing it properly later.

**Comment by achim-k** [comment]
Closing as https://github.com/RoboStack/ros-noetic/pull/345 has been merged

**Pull request closed without merging**
